[build]
  publish = "dist"
  command = "npm run build"

[build.processing]
  js = true
  css = true
  html = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
